language: ruby
cache: bundler
rvm:
- "2.5.7"
- "2.6.5"
- ruby-head
- jruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
  - rvm: jruby-head
  fast_finish: true
after_script: bundle exec codeclimate-test-reporter
